packages:
  - 'packages/*'
  - 'apps/lmnp/*'
  - 'libs/*'
  - 'libs/lmnp/*'
  - 'libs/utils/*'
autoInstallPeers: true
catalog:
  lucide-react: '0.545.0'
  react: '19.0.0'
  react-dom: '19.0.0'
  "zod": "4.1.12"
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'unrs-resolver'
strictPeerDependencies: false
